### ISSUE TITLE
Support for JValue scalar

### ISSUE THREAD

**Issue by ingemaradahl** [sangria-graphql/sangria-json4s-jackson#1]
Hi, and first off; thank you for a magnificent library!

I'm currently modeling a GraphQL schema using Sangria, and it's working very well so far. Different components of the schema are generated from multiple already existing metadata models for out data and for all data which is structured this has been progressing smoothly. However, some of our data is unstructured and consistently treated as Json.

https://gist.github.com/OlegIlyenko/5b96f4b54f656aac226d3c4bc33fd2a6 describes how to implement a scalar type which coerces to the raw json data, which is a subset of what I need. However, I don't want to copy the json4s-jackson marshalling library just to make one trivial change:

```diff
diff --git a/src/main/scala/sangria/marshalling/json4s/jackson.scala b/src/main/scala/sangria/marshalling/json4s/jackson.scala
index 954d769..36bb773 100644
--- a/src/main/scala/sangria/marshalling/json4s/jackson.scala
+++ b/src/main/scala/sangria/marshalling/json4s/jackson.scala
@@ -32,6 +32,7 @@ object jackson extends Json4sJacksonSupportLowPrioImplicits {
       case v: Double ⇒ JDouble(v)
       case v: BigInt ⇒ JInt(v)
       case v: BigDecimal ⇒ JDecimal(v)
+      case v: JValue ⇒ v
       case v ⇒ throw new IllegalArgumentException("Unsupported scalar value: " + v)
     }
 
```

which enables me to define my own `ScalarType[JValue]` which can be used whenever a request for unstructured data is made.

Would you accept this change upstream? I understand that it is a bit controversial, but users still would have to manually add their own scalar type to be able to use Json for input/output, so I hope the lure of using the backdoor is still far away enough..

**Comment by OlegIlyenko** [comment]
Thanks for raising this issue. Over the time I also came to a conclusion that while JSON scalar might be quite dangerous and needs serious consideration, there are some valid use-cases for it. 

I have less concerns about the output types, but the representation of input type is what concerns me the most, it is still vaguely defined. For example right now the unmarshaller [considers all nodes to be scalar nodes](https://gist.github.com/OlegIlyenko/5b96f4b54f656aac226d3c4bc33fd2a6#file-customjsonscalartype-scala-L69) it is potentially dangerous and might produce unexpecded behavious in some functionaly that is ouside of the querey execution core. Moreover, different libraries define it in different forms and there is no clear consensus (as literal JSON and as a string containing JSON), at least when it comes to a representation in the query AST (it's a bit easier when value comes from a variable).

So I can't give the answer on what would be the best way to introduce it right now, but I will think about it. In general I would be happy to accept such change, I just not yet sure would would be the best approach. In a gist the result marshaller is ok as-is I think, but it might be necessary to put more work in input unmarshaller.

**Comment by ingemaradahl** [comment]
Would you accept the partial change which would just modify the output marshalling to permit emitting JSON as a scalar? For consistency it would probably make sense to make the change across all the different marshalling libraries under the `sangria-graphql` umbrella. I'd love to help out with input marshalling too, but it seems like core changes needs to be made which I'm not comfortable with..

**Comment by ingemaradahl** [comment]
Hi again Oleg. I've now reached a point where I need to process "unstructured" data, meaning I need some way to both receive and emit JSON scalars. Have you had any chance to think about the problem of input unmarshalling? I'd love to help out, if you just point me in the right direction :sweat_smile:

**Comment by yanns** [comment]
For input marshalling, we find a solution in https://github.com/sangria-graphql/sangria-federated
